[project]
name = "fareflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "boto3>=1.40.23",
    "minio>=7.2.16",
    "python-decouple>=3.8",
]
