FROM bitnami/spark:3.4.3

USER root
RUN install_packages python3-pip && \
    pip3 install --no-cache-dir \
      pyspark==3.4.0 \
      delta-spark==2.4.0 \
      python-dotenv==1.0.1 \
      typer==0.12.5 \
      rich==13.7.1 \
      python-decouple \
      boto3 \
      requests

WORKDIR /opt/project
ENV PYTHONPATH=/opt/project
USER 1001
